DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS quiz;
DROP TABLE IF EXISTS score;

CREATE TABLE "student" (
	"ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"First_name"	TEXT NOT NULL,
	"Last_name"	TEXT NOT NULL
);

CREATE TABLE "quiz" (
	"ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT NOT NULL,
	"Questions"	INTEGER,
	"Date"	TEXT
);

CREATE TABLE "score" (
	"Student_ID"	INTEGER NOT NULL,
	"Quiz_ID"	INTEGER NOT NULL,
	"Score"	INTEGER NOT NULL
);